# gitzone standard
image: hosttoday/ht-docker-node:npmts

stages:
- test
- release
- trigger
- pages

testLEGACY:
  stage: test
  script:
    - npmci test legacy
  coverage: /Lines\s\s\s\s\s\s\s\s:\s\d+.\d+\%/
  tags:
    - docker
  allow_failure: true

testLTS:
  stage: test
  script:
    - npmci test lts
  coverage: /Lines\s\s\s\s\s\s\s\s:\s\d+.\d+\%/
  tags:
    - docker
    
testSTABLE:
  stage: test
  script:
    - npmci test stable
  coverage: /Lines\s\s\s\s\s\s\s\s:\s\d+.\d+\%/
  tags:
    - docker

release:
  stage: release
  script:
    - npmci publish
  only:
    - tags
  tags:
    - docker

trigger:
  stage: trigger
  script:
    - npmci trigger
  only:
    - tags
  tags:
    - docker

pages:
  image: hosttoday/ht-docker-node:npmpage
  stage: pages
  script:
    - npmci command npmpage --publish gitlab
  only:
    - tags
  artifacts:
    expire_in: 1 week
    paths:
    - public
